package main

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/ipapakonstantinou/tut_go-basics/pkg"

)



type empData struct {
    Name string
    Age string
    City string
}

func readEmpData() {

    csvFile, err := os.Open("emp.csv")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("Successfully Opened CSV file")
	defer csvFile.Close()
    
    csvLines, err := csv.NewReader(csvFile).ReadAll()
    if err != nil {
        fmt.Println(err)
    }    
    for _, line := range csvLines {
        emp := empData{
            Name: line[0],
            Age: line[1],
			City: line[2],
        }
        fmt.Println(emp.Name + " " + emp.Age + " " + emp.City)
    }
}


func main() {

	auth_token := config.LoadConfig()

    c := http.Client{Timeout: time.Duration(3) * time.Second}
    req, err := http.NewRequest("GET", "https://api.twitter.com/2/tweets/search/recent?query=btc&tweet.fields=author_id,created_at,entities,geo,in_reply_to_user_id,lang,possibly_sensitive,referenced_tweets,source", nil)

    if err != nil {
        log.Fatal(err)
    }

    req.Header.Add("Authorization", auth_token)
    resp, err := c.Do(req)

	bytes, errRead := ioutil.ReadAll(resp.Body)
	if errRead != nil {
		log.Fatal(errRead)
	}
	// log.Print(string(bytes))
	fmt.Printf(string(bytes))


	type TweetsStructure struct {
		Data []struct {
			ID   string `json:"id"`
			Text string `json:"text"`
		} `json:"data"`
		Meta struct {
			NewestID    string `json:"newest_id"`
			OldestID    string `json:"oldest_id"`
			ResultCount int    `json:"result_count"`
			NextToken   string `json:"next_token"`
		} `json:"meta"`
	}

	var tweets TweetsStructure
	json.Unmarshal(bytes, &tweets)

	for i := 0; i < len(tweets.Data); i++ {
		fmt.Println()
		fmt.Println("Twitter ID: " + tweets.Data[i].ID)

		twitter_text := tweets.Data[i].Text
		// twitter_text := emoji.RemoveAll(tweets.Data[i].Text)
		fmt.Println("Twitter Text: " + twitter_text)
		// fmt.Println("User Age: " + strconv.Itoa(users.Data[i].Text))
		// fmt.Println("User Name: " + users.Data[i].Name)
		// fmt.Println("Facebook Url: " + users.AutoGenerated[i].Social.Facebook)
	}
}